[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
    "pip install uv",
    "uv pip install -r requirements.txt --system"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "./start.sh"