[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
    "echo '📦 Installing dependencies with pip...'",
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "echo '✅ Dependencies installed successfully'"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python run_server.py"