[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
    "pip install uv",
    "uv sync --frozen"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "uv run python railway_start.py"